### PR TITLE
includes HR in the trace

### PR DESCRIPTION
**Pull request by leonardomaccari**
Hi, I added the HR value to the new exported.

### CODE REVIEW

**Comment by cmaion** [comment]
Hi

Finally took some time to look into this.
It seems that other apps are adding HR data to the GPX file in a different way, so I have reimplemented your commit following what I saw.

Pull and test commit 4cdf648a2d383a8d82c83ae5e6957cecf927d4db!

**Comment by leonardomaccari** [comment]
Hi,

The patch does not work for me. First I have an error in the round(1) function, which does not seem to exist:

```
./polar_training2gpx:60:in `block (8 levels) in output_gpx': undefined method `round' for nil:NilClass (NoMethodError)
	from /home/leonardo/.rvm/gems/ruby-2.2.1/gems/nokogiri-1.8.0/lib/nokogiri/xml/builder.rb:391:in `call'
	from /home/leonardo/.rvm/gems/ruby-2.2.1/gems/nokogiri-1.8.0/lib/nokogiri/xml/builder.rb:391:in `insert'
	from /home/leonardo/.rvm/gems/ruby-2.2.1/gems/nokogiri-1.8.0/lib/nokogiri/xml/builder.rb:375:in `method_missing'
	from ./polar_training2gpx:59:in `block (7 levels) in output_gpx'
	from /home/leonardo/.rvm/gems/ruby-2.2.1/gems/nokogiri-1.8.0/lib/nokogiri/xml/builder.rb:391:in `call'
	from /home/leonardo/.rvm/gems/ruby-2.2.1/gems/nokogiri-1.8.0/lib/nokogiri/xml/builder.rb:391:in `insert'
	from /home/leonardo/.rvm/gems/ruby-2.2.1/gems/nokogiri-1.8.0/lib/nokogiri/xml/builder.rb:375:in `method_missing'
	from ./polar_training2gpx:58:in `block (6 levels) in output_gpx'
	from /home/leonardo/.rvm/gems/ruby-2.2.1/gems/nokogiri-1.8.0/lib/nokogiri/xml/builder.rb:391:in `call'
	from /home/leonardo/.rvm/gems/ruby-2.2.1/gems/nokogiri-1.8.0/lib/nokogiri/xml/builder.rb:391:in `insert'
	from /home/leonardo/.rvm/gems/ruby-2.2.1/gems/nokogiri-1.8.0/lib/nokogiri/xml/builder.rb:375:in `method_missing'
	from ./polar_training2gpx:55:in `block (5 levels) in output_gpx'
	from ./polar_training2gpx:54:in `each'
	from ./polar_training2gpx:54:in `block (4 levels) in output_gpx'
	from /home/leonardo/.rvm/gems/ruby-2.2.1/gems/nokogiri-1.8.0/lib/nokogiri/xml/builder.rb:391:in `call'
	from /home/leonardo/.rvm/gems/ruby-2.2.1/gems/nokogiri-1.8.0/lib/nokogiri/xml/builder.rb:391:in `insert'
	from /home/leonardo/.rvm/gems/ruby-2.2.1/gems/nokogiri-1.8.0/lib/nokogiri/xml/builder.rb:375:in `method_missing'
	from ./polar_training2gpx:52:in `block (3 levels) in output_gpx'
	from /home/leonardo/.rvm/gems/ruby-2.2.1/gems/nokogiri-1.8.0/lib/nokogiri/xml/builder.rb:391:in `call'
	from /home/leonardo/.rvm/gems/ruby-2.2.1/gems/nokogiri-1.8.0/lib/nokogiri/xml/builder.rb:391:in `insert'
	from /home/leonardo/.rvm/gems/ruby-2.2.1/gems/nokogiri-1.8.0/lib/nokogiri/xml/builder.rb:375:in `method_missing'
	from ./polar_training2gpx:51:in `block (2 levels) in output_gpx'
	from /home/leonardo/.rvm/gems/ruby-2.2.1/gems/nokogiri-1.8.0/lib/nokogiri/xml/builder.rb:391:in `call'
	from /home/leonardo/.rvm/gems/ruby-2.2.1/gems/nokogiri-1.8.0/lib/nokogiri/xml/builder.rb:391:in `insert'
	from /home/leonardo/.rvm/gems/ruby-2.2.1/gems/nokogiri-1.8.0/lib/nokogiri/xml/builder.rb:375:in `method_missing'
	from ./polar_training2gpx:40:in `block in output_gpx'
	from /home/leonardo/.rvm/gems/ruby-2.2.1/gems/nokogiri-1.8.0/lib/nokogiri/xml/builder.rb:293:in `initialize'
	from ./polar_training2gpx:39:in `new'
	from ./polar_training2gpx:39:in `output_gpx'
	from ./polar_training2gpx:79:in `block in <main>'
	from ./polar_training2gpx:78:in `open'
	from ./polar_training2gpx:78:in `<main>'
```


If I remove the the call to round(1), the gpx is created but the program I use to read it (turtlesport, it's open source) says it is invalid. No problem with my version

**Comment by cmaion** [comment]
Pull & try again.
The error you had is due to the fact that your device don't record temperature samples, should be fixed.

I gave turtlesport a quick try -- it has been able to import my last session successfully.

**Comment by leonardomaccari** [comment]
still no luck. as expected the round() error does not happen, but I still get an error from turtlesport. What data do you want me to share to reproduce?

**Comment by cmaion** [comment]
OK zip a training session folder (everything in ~/Polar/<serial>/U/0/<yyyymmdd>/E/<id>) and share it somewhere so that I can take a look at what happens

**Pull request closed without merging**
